name: Build and Upload Data Management App

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build the app from'
        required: false
        default: 'main'
      tag_name:
        description: 'Tag to apply to the built artifact'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Determine ref
        id: determine_ref
        run: |
          echo "ref=${{ github.event.release.tag_name || github.event.inputs.branch || 'main' }}" >> $GITHUB_OUTPUT

      - name: Checkout Data Management App Repo
        uses: actions/checkout@v4
        with:
          repository: hydroserver2/hydroserver-data-management-app
          ref: ${{ steps.determine_ref.outputs.ref }}
          path: data_mgmt

      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: data_mgmt/package-lock.json

      - name: Install Dependencies
        working-directory: ./data_mgmt
        run: npm ci

      - name: Configure Environment Variables
        working-directory: ./data_mgmt
        run: |
          cat << EOF > .env
          VITE_APP_VERSION=${{ github.event.release.tag_name || github.event.inputs.tag_name }}
          VITE_APP_GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}
          VITE_APP_GOOGLE_MAPS_MAP_ID=${{ secrets.GOOGLE_MAPS_MAP_ID }}
          VITE_APP_PROXY_BASE_URL=${{ vars.PROXY_BASE_URL }}
          EOF

      - name: Build Data Management App
        working-directory: ./data_mgmt
        run: npm run build

      - name: Upload versioned artifact
        uses: actions/upload-artifact@v3
        with:
          name: data-management-app-${{ github.event.release.tag_name || github.event.inputs.tag_name }}
          path: ./data_mgmt/dist

      - name: Upload latest artifact
        if: ${{ github.event_name == 'release' }}
        uses: actions/upload-artifact@v3
        with:
          name: data-management-app-latest
          path: ./data_mgmt/dist
